// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: az4W6VXcp4Uq4NJ5GtxTg5
// Component: t6-6051BEW
import * as React from "react";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Avatar from "../../Avatar"; // plasmic-import: vXSjmOQDKr/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_whatsapp_chat_app.module.css"; // plasmic-import: az4W6VXcp4Uq4NJ5GtxTg5/projectcss
import sty from "./PlasmicUploadAvatar.module.css"; // plasmic-import: t6-6051BEW/css

export const PlasmicUploadAvatar__VariantProps = new Array();

export const PlasmicUploadAvatar__ArgProps = new Array();

export const defaultUploadAvatar__Args = {};

function PlasmicUploadAvatar__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultUploadAvatar__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Avatar
        data-plasmic-name={"avatar"}
        data-plasmic-override={overrides.avatar}
        className={classNames("__wab_instance", sty.avatar)}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "avatar"],
  avatar: ["avatar"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicUploadAvatar__ArgProps,
      internalVariantPropNames: PlasmicUploadAvatar__VariantProps
    });

    return PlasmicUploadAvatar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUploadAvatar";
  } else {
    func.displayName = `PlasmicUploadAvatar.${nodeName}`;
  }
  return func;
}

export const PlasmicUploadAvatar = Object.assign(
  // Top-level PlasmicUploadAvatar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    avatar: makeNodeComponent("avatar"),
    // Metadata about props expected for PlasmicUploadAvatar
    internalVariantProps: PlasmicUploadAvatar__VariantProps,
    internalArgProps: PlasmicUploadAvatar__ArgProps
  }
);

export default PlasmicUploadAvatar;
/* prettier-ignore-end */
