// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: az4W6VXcp4Uq4NJ5GtxTg5
// Component: YuVt1lzfc5
import * as React from "react";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_whatsapp_chat_app.module.css"; // plasmic-import: az4W6VXcp4Uq4NJ5GtxTg5/projectcss
import sty from "./PlasmicLogoutIcon.module.css"; // plasmic-import: YuVt1lzfc5/css
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: apCUQX7qw7/icon

export const PlasmicLogoutIcon__VariantProps = new Array();

export const PlasmicLogoutIcon__ArgProps = new Array();

export const defaultLogoutIcon__Args = {};

function PlasmicLogoutIcon__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultLogoutIcon__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};
  return (
    <VectorIcon
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      role={"img"}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLogoutIcon__ArgProps,
      internalVariantPropNames: PlasmicLogoutIcon__VariantProps
    });

    return PlasmicLogoutIcon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogoutIcon";
  } else {
    func.displayName = `PlasmicLogoutIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicLogoutIcon = Object.assign(
  // Top-level PlasmicLogoutIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicLogoutIcon
    internalVariantProps: PlasmicLogoutIcon__VariantProps,
    internalArgProps: PlasmicLogoutIcon__ArgProps
  }
);

export default PlasmicLogoutIcon;
/* prettier-ignore-end */
