// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: az4W6VXcp4Uq4NJ5GtxTg5
// Component: t6-6051BEW
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Avatar from "../../Avatar"; // plasmic-import: vXSjmOQDKr/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_whatsapp_chat_app.module.css"; // plasmic-import: az4W6VXcp4Uq4NJ5GtxTg5/projectcss
import sty from "./PlasmicUploadAvatar.module.css"; // plasmic-import: t6-6051BEW/css
import Rolling1S200PxsvgIcon from "./icons/PlasmicIcon__Rolling1S200Pxsvg"; // plasmic-import: gr_4w0Fso/icon

export const PlasmicUploadAvatar__VariantProps = new Array(
  "isError",
  "isLoading"
);

export const PlasmicUploadAvatar__ArgProps = new Array("errorMessage");

export const defaultUploadAvatar__Args = {};

function PlasmicUploadAvatar__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultUploadAvatar__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {(hasVariant(variants, "isLoading", "isLoading") ? true : true) ? (
        <Avatar
          data-plasmic-name={"avatar"}
          data-plasmic-override={overrides.avatar}
          className={classNames("__wab_instance", sty.avatar, {
            [sty.avatarisLoading]: hasVariant(
              variants,
              "isLoading",
              "isLoading"
            )
          })}
        />
      ) : null}
      {(hasVariant(variants, "isError", "isError") ? true : true) ? (
        <div
          className={classNames(projectcss.all, sty.freeBox__kamv2, {
            [sty.freeBoxisError__kamv2WaVNr]: hasVariant(
              variants,
              "isError",
              "isError"
            )
          })}
        >
          <div
            className={classNames(projectcss.all, sty.freeBox__ikOo0, {
              [sty.freeBoxisError__ikOo0WaVNr]: hasVariant(
                variants,
                "isError",
                "isError"
              )
            })}
          >
            {p.renderPlasmicSlot({
              defaultContents: "Enter some text",
              value: args.errorMessage,
              className: classNames(sty.slotTargetErrorMessage, {
                [sty.slotTargetErrorMessageisError]: hasVariant(
                  variants,
                  "isError",
                  "isError"
                )
              })
            })}
          </div>
        </div>
      ) : null}
      {(hasVariant(variants, "isLoading", "isLoading") ? true : true) ? (
        <div
          className={classNames(projectcss.all, sty.freeBox__d9NBj, {
            [sty.freeBoxisLoading__d9NBjKbaZ]: hasVariant(
              variants,
              "isLoading",
              "isLoading"
            )
          })}
        >
          {(hasVariant(variants, "isLoading", "isLoading") ? true : false) ? (
            <Rolling1S200PxsvgIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg, {
                [sty.svgisLoading]: hasVariant(
                  variants,
                  "isLoading",
                  "isLoading"
                )
              })}
              role={"img"}
            />
          ) : null}
        </div>
      ) : null}
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "avatar", "svg"],
  avatar: ["avatar"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicUploadAvatar__ArgProps,
      internalVariantPropNames: PlasmicUploadAvatar__VariantProps
    });

    return PlasmicUploadAvatar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUploadAvatar";
  } else {
    func.displayName = `PlasmicUploadAvatar.${nodeName}`;
  }
  return func;
}

export const PlasmicUploadAvatar = Object.assign(
  // Top-level PlasmicUploadAvatar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    avatar: makeNodeComponent("avatar"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicUploadAvatar
    internalVariantProps: PlasmicUploadAvatar__VariantProps,
    internalArgProps: PlasmicUploadAvatar__ArgProps
  }
);

export default PlasmicUploadAvatar;
/* prettier-ignore-end */
